### ISSUE TITLE
Sagemath9.3 couldn't find the sboxanalyzer 

### ISSUE THREAD

**Issue by mtori-e** [hadipourh/sboxanalyzer#2]
Hi every one :) 

I have been trying to import sboxanalyzer in to sagemath , but sagemath couldn't find the model.
I am using windows 10 ,and I have sagemath 9.3 , also i download Espresso and make it . Espresso , sboxanalyzer  in the same directory of sagemath. I don't know what wrong ? 
I will attach a printscreen of the working directory folder of sage and printscreen of sagemath console.

thanks in Advance ,
[Meaad]
![image](https://user-images.githubusercontent.com/55367493/183003555-ef40d987-eb52-4d46-a040-39e3221b4c9f.png)

![image](https://user-images.githubusercontent.com/55367493/183003590-fdd0b597-0a1e-40fc-8b88-ac7f83b3a90f.png)

**Comment by hadipourh** [comment]
Hi,

S-box Analyzer is originally developed in Linux. So, Linux users do not have this issue. However, it is also possible to use S-box Analyzer in windows. To do so, please follow the below steps and make sure if you have performed each step correctly:

- If you have managed to run the `make` command successfully, you should have a binary version of `espresso` program inside the bin folder. Please check it and make sure if it exists before going to the next steps.
- When you run the SageMath in windows, it has only access to its own virtual environment which is usually in this directory by default: `C:\Users\[YOUR_USER_NAME]\AppData\Local\SageMath 9.[X]\runtime\home\sage` (please replace `[YOUR_USER_NAME]` and `9.[X]` with your username and your SageMath version, respectively).
- Thus, one simple solution is copying the `sboxanalyzer` folder into the following path: `C:\Users\[YOUR_USER_NAME]\AppData\Local\SageMath 9.[X]\runtime\home\sage`. Next, run the SageMath and navigate into the `sboxanalyzer` folder by this command `cd sboxanalyzer` and then use the tool.

Please let me know if this solution does not work for you.

**Comment by mtori-e** [comment]
Hi Hossain ,
 🙂


Now I copy the folder in the write directory 

![image](https://user-images.githubusercontent.com/55367493/183270683-1e43b3d6-3b58-48b7-9f38-b9a48fdf011a.png)

is there a way to navigate in sagmath other than cd ? I tried it, but it didn't work 
![image](https://user-images.githubusercontent.com/55367493/183270659-16bda1fc-03bb-4bb2-9de7-748fabcc389e.png)

I use 'help() ' in sagemath console and couldn't find cd between the commands !
There is a load and attach command. Is this necessary to load the tool?

I try to use load and print the same path of the folder but it also did not work !
![image](https://user-images.githubusercontent.com/55367493/183270637-76ae5ac8-19be-48c2-8a58-d3c6cf8d6878.png)

**Comment by mtori-e** [comment]
Now I found that  its start to import when i change copy the files in to 
c:\users\[myusername ]




now I am facing another problem !!


![image](https://user-images.githubusercontent.com/55367493/183272116-1028b166-1d5d-465f-bd2d-47cba031ca62.png)


do you have any idea?

**Comment by hadipourh** [comment]
I guess there is something wrong with the binary version of ESPRESSO on your computer. I am not sure if you have successfully compiled it. However, you can download the binary version of ESPRESSO from [here](https://github.com/hadipourh/logic-minimization/blob/master/espresso.exe) (please put it inside the bin folder afterward).

Some comments regarding the images you have already attached:

- You have not used the directory I mentioned. Please compare the path in your picture with what I mentioned. They are totally different!
- `cd` works in SageMath (both Windows and Linux versions). As you can see in the picture you have attached, it outputs `No such file or directory ...` which means you have copied `sboxanalyzer` in a wrong place (different than what I mentioned).
- If you have copied `sboxanalyzer` folder in a different directory and you have managed to successfully import it into the SageMath, please mention the exact directory here. I think, it helps other potential Windows users who may face the same issue. 

Hope that it helps :-)

Please let me know if this solution works.

**Comment by mtori-e** [comment]
I reinstall sagemath and this time I  don't choose the directory, I use  same the installer setting and follow the instruction from the previous comment . Also , it seems that my system didn't make espresso correctly so I download the binary version of ESPRESSO from the previous reply and paste it in bin folder that belongs to espresso  .. and it works :

a print screen of the binary version path of espresso 
![image](https://user-images.githubusercontent.com/55367493/183341780-371cb07e-834b-4138-b926-c9f97174979b.png)


a print screen of sboxanalyzer folder path 
![image](https://user-images.githubusercontent.com/55367493/183341874-d8cdb10f-4c88-40f9-a418-50f6cc97f5ad.png)


a print screen of the result :

![image](https://user-images.githubusercontent.com/55367493/183341520-8691a4a2-50ff-408a-aa36-595bebf279c5.png)



Thank you so much Hossain ,
Meaad

**Comment by hadipourh** [comment]
Happy that it worked and hope this tool will be useful for you.
